GET http://localhost:1234/dbTest/users HTTP/1.1
Authorization: baerel eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmU2OGRkNmU2N2NlNWUyMDFkOWFlODQiLCJpYXQiOjE2NTkyODA5ODUsImV4cCI6MTY1OTI4Mzk4NX0.uN4KskA857MN-97nJGT3TwOfltbET13AA1ae2n2yALQ
