GET http://localhost:1234/dbTest/adminPages HTTP/1.1
Authorization: baerel eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmU2YTFlMTg2ZGQ5ZWQ5MGY1YzU0MTYiLCJpYXQiOjE2NTkyODE5MDAsImV4cCI6MTY1OTI4NDkwMH0.OD_eYKU-PeOq7Q2rlxQJD1T7d9EaQmxgZIEr-XHwIO8
