GET http://localhost:1234/auth/checkToken/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmU2OGRkNmU2N2NlNWUyMDFkOWFlODQiLCJpYXQiOjE2NTkyODU1MjMsImV4cCI6MTY1OTI4ODUyM30._kdiuvKtAE4pgL14uyvIP40C0m1EbRx_Q4URCR5BOC0 HTTP/1.1